# Generated by Django 3.0.4 on 2020-04-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gross_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('featured', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grocery Item',
                'verbose_name_plural': 'Grocery Items',
                'ordering': ('updated',),
            },
        ),
        migrations.CreateModel(
            name='GroceryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='grocery_category_feature_image')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grocery Category',
                'verbose_name_plural': 'Grocery Categories',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='GroceryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.Grocery')),
            ],
        ),
        migrations.CreateModel(
            name='GroceryReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('rating_1', models.BooleanField(default=False)),
                ('rating_2', models.BooleanField(default=False)),
                ('rating_3', models.BooleanField(default=False)),
                ('rating_4', models.BooleanField(default=False)),
                ('rating_5', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.Grocery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='grocery_images')),
                ('is_featured', models.BooleanField(default=False)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.Grocery')),
            ],
        ),
        migrations.AddField(
            model_name='grocery',
            name='grocery_category',
            field=models.ManyToManyField(to='grocery.GroceryCategory'),
        ),
    ]
