# Generated by Django 3.0.4 on 2020-04-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_auto_20200419_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='grocery_category',
        ),
        migrations.AddField(
            model_name='grocery',
            name='grocery_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grocery.GroceryCategory'),
        ),
    ]
