# Generated by Django 3.0.4 on 2020-04-19 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_auto_20200419_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grocery.GrocerySubCategory'),
        ),
    ]
