# Generated by Django 3.0.4 on 2020-05-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_auto_20200420_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fullfilled', models.BooleanField(default=False, help_text='If request is fullfilled, Put if True')),
            ],
        ),
    ]
