# Generated by Django 3.0.4 on 2020-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_groceryrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='scale',
            field=models.CharField(choices=[('gram', 'Gram'), ('kg', 'Kilogram'), ('ml', 'MiliLitre'), ('l', 'Litre')], default='kg', max_length=100),
        ),
    ]
