# Generated by Django 3.0.4 on 2020-07-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_auto_20200710_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryreview',
            name='rating_2',
        ),
        migrations.RemoveField(
            model_name='groceryreview',
            name='rating_3',
        ),
        migrations.RemoveField(
            model_name='groceryreview',
            name='rating_4',
        ),
        migrations.RemoveField(
            model_name='groceryreview',
            name='rating_5',
        ),
        migrations.RemoveField(
            model_name='groceryreview',
            name='updated',
        ),
    ]
