# Generated by Django 3.0.4 on 2020-03-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200314_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelreservation',
            options={'verbose_name': 'Restaurant Reservation', 'verbose_name_plural': 'Restaurant Reservations'},
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
