# Generated by Django 3.0.4 on 2020-03-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200315_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelreservation',
            name='date',
        ),
    ]
