# Generated by Django 3.0.4 on 2020-03-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_hotelreservation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelReservation',
        ),
    ]
