# Generated by Django 3.0.4 on 2020-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='business_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='business_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='country',
            field=models.CharField(choices=[('india', 'India')], default='india', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='state',
            field=models.CharField(choices=[('uttarakhand', 'Uttarakhand')], default='uttarakhand', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residentialpincode',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='residentialpincode',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', help_text="User's Email", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(help_text="User's full name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER'), ('PREFER_NOT_TO_SAY', 'PREFER_NOT_TO_SAY')], help_text="User's Gender", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(help_text="User's Mobile number", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(help_text="User's unique user id, keep it irrelated with respect to your name or email.", max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='business_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='country',
            field=models.CharField(choices=[('india', 'India')], default='india', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(choices=[('uttarakhand', 'Uttarakhand')], default='uttarakhand', max_length=255, null=True),
        ),
    ]
