# Generated by Django 3.0.4 on 2020-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200314_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
