# Generated by Django 3.0.4 on 2020-04-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_auto_20200420_0149'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='groceries',
            field=models.ManyToManyField(to='grocery.Grocery'),
        ),
    ]
