# Generated by Django 3.0.4 on 2020-04-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
