# Generated by Django 3.0.4 on 2020-04-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_auto_20200420_0149'),
        ('products', '0005_remove_food_collection'),
        ('cart', '0006_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.Grocery')),
            ],
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Food')),
            ],
        ),
    ]
