# Generated by Django 3.0.4 on 2020-04-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_foodentry_groceryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='foods',
            field=models.ManyToManyField(to='cart.FoodEntry'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='groceries',
            field=models.ManyToManyField(to='cart.GroceryEntry'),
        ),
    ]
