# Generated by Django 3.0.4 on 2020-07-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200421_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='foods',
            field=models.ManyToManyField(blank=True, to='cart.FoodEntry'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='groceries',
            field=models.ManyToManyField(blank=True, to='cart.GroceryEntry'),
        ),
    ]
