# Generated by Django 3.0.4 on 2020-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category_feature_image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='summary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, upload_to='collection_feature_image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='summary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='gross_price',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparation_time',
            field=models.CharField(help_text='In minutes', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='summary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='tax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(choices=[('india', 'India')], default='india', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='mobile_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(choices=[('uttarakhand', 'Uttarakhand')], default='uttarakhand', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
