# Generated by Django 3.0.4 on 2020-03-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='products.Restaurant'),
        ),
    ]
