# Generated by Django 3.0.4 on 2020-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200314_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='original_price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
