# Generated by Django 3.0.4 on 2020-03-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='foods',
        ),
    ]
