# Generated by Django 3.0.4 on 2020-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_collection_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='collection',
            field=models.ManyToManyField(to='products.Collection'),
        ),
    ]
