# Generated by Django 3.0.4 on 2020-03-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_food_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='collection',
        ),
    ]
